=== mmbase/te/src/te/template.dtd
<!ELEMENT template (component*|container*)>
<!ATTLIST template 
	name CDATA #REQUIRED 
	layout CDATA #IMPLIED>

<!ELEMENT property (#PCDATA)>
<!ATTLIST property name CDATA #REQUIRED>

<!ELEMENT container (component* | container* | property*)>
<!ATTLIST container 
	name CDATA #REQUIRED
	layout CDATA #IMPLIED>
<!ELEMENT component (property*)>
<!ATTLIST component 
	name CDATA #REQUIRED
	layout CDATA #IMPLIED>

=== mmbase/te/src/nl/vpro/mmbase/applications/te/newspage.xml
<?xml version="1.0"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template name="default" layout="default" description="pagina om een news weer te geven">
  <component name="page_head"/>
  <component name="logo"/>
  <component name="navigation"/>
  <container name="horizontal" layout="horizontal">
    <container name="vertical">
	    <component name="related_images"/>
    </container>
    <container name="vertical">
        <component name="news_prev_next"/>
       <component name="news"/>
    </container>
    <component name="related_audio_video"/>
  </container>
</template>

=== mmbase/te/src/nl/vpro/mmbase/applications/te/episodepage.xml
<?xml version="1.0"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template name="default" layout="default" description="pagina om een aflevering te laten zien">
  <component name="page_head"/>
  <component name="logo"/>
  <component name="navigation"/>
  <container name="horizontal" layout="horizontal">
    <container name="vertical">
      <component name="episode_name"/>
      <component name="related_images"/>
    </container>
    <container name="vertical">
      <component name="episode_title"/>
      <component name="episode_previousnext"/>
      <component name="episode_body"/>
    </container>
    <component name="related_audio_video"/>
  </container>
</template>

=== mmbase/te/src/te/episodeshomepage.xml
<?xml version="1.0"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template name="default" layout="default">
  <component name="te.jsp.JSPComponent//te/component/page_head.jsp"/>
  <component name="nl.vpro.ProgrammaSiteNavigationComponent//te/component/navigation.jsp">
    <property name="showBinders">flase</property>
    <property name="showArchives">flase</property>
    <property name="showForums">flase</property>
    <property name="showLogs">flase</property>
  </component>
  <container name="horizontal">
    <component name="te.jsp.JSPComponent//te/component/maps.jsp"/>
    <container name="vertical"/>
    <component name="te.jsp.JSPComponent//te/component/related_news.jsp"/>
  </container>
</template>
