=== mmbase/te/src/te/template.dtd
<!ELEMENT template (component*|container*)>
<!ATTLIST template 
	name CDATA #REQUIRED 
	layout CDATA #IMPLIED>

<!ELEMENT property (#PCDATA)>
<!ATTLIST property name CDATA #REQUIRED>

<!ELEMENT container (component* | container* | property*)>
<!ATTLIST container 
	name CDATA #REQUIRED
	layout CDATA #IMPLIED>
<!ELEMENT component (property*)>
<!ATTLIST component 
	name CDATA #REQUIRED
	layout CDATA #IMPLIED>

=== mmbase/te/src/nl/vpro/serviceinfopage.xml
<?xml version="1.0"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template name="default" layout="default" description="service info page">
  <component name="page_head"/>
  <component name="logo"/>
  <component name="navigation"/>
  <container name="horizontal" layout="horizontal">
    <container name="vertical">
      <component name="breadcrum"/>
      <component name="serviceinfo_other"/>
    </container>
    <component name="serviceinfo"/>
    <container name="vertical">
      <component name="related_audio_video"/>
      <component name="related_other"/>
    </container>
  </container>
</template>

=== mmbase/te/src/nl/vpro/newspage.xml
<?xml version="1.0"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template name="default" layout="default" description="pagina om een news weer te geven">
  <component name="page_head"/>
  <component name="logo"/>
  <component name="navigation"/>
  <container name="horizontal" layout="horizontal">
    <container name="vertical">
   	    <component name="breadcrum"/>
	    <component name="related_images"/>
    </container>
    <component name="news"/>
    <component name="related_audio_video"/>
  </container>
</template>

=== mmbase/te/src/nl/vpro/teasershomepage.xml
<?xml version="1.0"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template name="default" layout="default" description="voorpagina met teasers">
  <component name="page_head"/>
  <component name="logo"/>
  <component name="navigation"/>
  <container name="horizontal" layout="horizontal">
    <component name="home_maps"/>
    <container name="vertical">
      <component name="home_superteaser"/>
      <component name="home_teasers"/>
    </container>
    <component name="home_related_news"/>
  </container>
</template>

=== mmbase/te/src/nl/vpro/mmbase/applications/te/magazinehomepage.xml
<?xml version="1.0"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template name="programmasites" layout="default" description="voorpagina met als hoofd item een magazine">
  <component name="page_head"/>
  <component name="logo"/>
  <component name="navigation"/>
  <container name="horizontal" layout="horizontal">
    <component name="home_maps"/>
    <container name="vertical">
      <component name="home_superteaser"/>
      <component name="home_magazine"/>
    </container>
    <component name="home_related_episodes"/>
  </container>
</template>

=== mmbase/te/src/nl/vpro/itempage.xml
<?xml version="1.0"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template name="default" layout="default">
  <component name="page_head"/>
  <component name="navigation">
    <property name="showBinders">flase</property>
    <property name="showArchives">flase</property>
    <property name="showForums">flase</property>
    <property name="showLogs">flase</property>
  </component>
  <container name="horizontal" layout="horizontal">
     <component name="item_siblings"/>
    <container name="vertical">
            <component name="item_title"/>
            <component name="item_nav"/>
            <component name="item_body"/>
    </container>
    <component name="item_related_audio_video"/>
  </container>
</template>

=== mmbase/te/src/nl/vpro/searchpage.xml
<?xml version="1.0"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template name="nocache" layout="default">
  <component name="page_head"/>
  <component name="navigation">
    <property name="showBinders">flase</property>
    <property name="showArchives">flase</property>
    <property name="showForums">flase</property>
    <property name="showLogs">flase</property>
  </component>
  <component name="search"/>
</template>

=== mmbase/te/src/nl/vpro/binderpage.xml
<?xml version="1.0"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template name="default" layout="default" description="pagina om een dossier te laten zien">
  <component name="page_head"/>
  <component name="logo"/>
  <component name="navigation"/>
  <container name="horizontal" layout="horizontal">
      <container name="vertical">
      	    <component name="breadcrum"/>
   	        <component name="binder"/>
     </container>
     <component name="binder_content"/>
     <component name="binder_related"/>
  </container>
</template>

=== mmbase/te/src/nl/vpro/episodeshomepage.xml
<?xml version="1.0"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template name="default" layout="default">
  <component name="page_head"/>
  <component name="navigation">
    <property name="showBinders">flase</property>
    <property name="showArchives">flase</property>
    <property name="showForums">flase</property>
    <property name="showLogs">flase</property>
  </component>
  <container name="horizontal" layout="horizontal">
    <component name="maps"/>
    <component name="related_news"/>
  </container>
</template>
